version: 2

builds:
  - main: ./cmd/gitlab-ci-crawler
    env:
      - CGO_ENABLED=0

dockers:
  - dockerfile: Dockerfile_release
    image_templates:
      - ghcr.io/catouc/gitlab-ci-crawler:latest
      - ghcr.io/catouc/gitlab-ci-crawler:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
      - ghcr.io/catouc/gitlab-ci-crawler:{{ .Major }}.{{ .Minor }}
      - ghcr.io/catouc/gitlab-ci-crawler:{{ .Major }}
